---
name: cron
on:
  schedule:
    - cron: "13 4 * * 1,3,5"
concurrency:
  group: cron
  cancel-in-progress: true
jobs:
  cron:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - run: bundle install
      - run: |
          bin/fief --token ${{ secrets.TOKEN }} --delay 1500 \
            --include jcabi/* \
            --include yegor256/* \
            --include sttc/* \
            --include zerocracy/* \
            --include zold-io/* \
            --exclude jcabi/.github \
            --exclude yegor256/quiz \
            --exclude yegor256/hangman \
            --exclude objectionary/.github \
            --exclude polystat/.github \
            --to gh-pages
      - run: mkdir -p gh-pages/$(date +'%Y/%m/%d')
      - run: cp gh-pages/index.xml gh-pages/$(date +'%Y/%m/%d')/index.xml
      - uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: gh-pages
          clean: false
